language: python
matrix:
    include:
        - python: 2.7
        - python: 3.6

branches:
    only:
        - master
        - devtest

install:
    - pip install -r requirements.txt
    - python setup.py install

script: python setup.py test
