environment:
    matrix:
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python36-x64"

branches:
  only:
  - master
  - devtest

before_build:
after_build:
build_script:

build: off

install:
    - "python -m pip install -r requirements.txt"
    - "python setup.py install"

test_script:
    - "python setup.py test"
